config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  root to: 'home#index'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :groups
  resources :operations

  resources :groups do
    member do
      get 'group_operations'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Group, user.id
    can :manage, Operation, user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_operations
  has_many :operations, through: :group_operations

  validates :name, presence: true, length: { in: 0..250 }
  validates :icon, presence: true, length: { in: 0..250 }

  def group_total
    # This is the purchases sum of one category
    operations.sum(:amount)
  end
end

# @total_purchases = current_user.purchases.includes(:categories).pluck(:amount).sum

app/models/group_operation.rb
class GroupOperation < ApplicationRecord
  belongs_to :group
  belongs_to :operation
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  has_many :group_operations
  has_many :groups, through: :group_operations
  accepts_nested_attributes_for :group_operations

  attr_accessor :extra_field

  validates :name, presence: true, length: { in: 0..250 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :operations
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_ressources)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def index
    @groups = Group.where(user_id: current_user.id).order(created_at: :desc)
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Category created successfully '
    else
      render 'new'
    end
  end

  def group_operations
    @group = Group.find(params[:id])
    @operation_group = Operation.left_outer_joins(:group_operations).where(group_operations: { group_id: @group.id },
                                                                           operations: { user_id: current_user.id })
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def new
    @operation = Operation.new
    @operation.group_operations.build
  end

  def create
    @operation = current_user.operations.build(operation_params)
    extra_data = params[:operation][:extra_field]
    if @operation.save
      @group_op = GroupOperation.new(operation: Operation.last, group_id: extra_data)
      redirect_to groups_path if @group_op.save
    else
      render 'new'
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount, group_operations_attributes: [:group_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/groups/group_operations.html.erb
<div class='mt-0' style='background-color: #3778c2'>
  <%= render 'shared/header' %>
</div>
<div>
<h2 class="text-primary"><%= @group.name %></h2>
<ul>
  <% @operation_group.each do |opera| %>
    <li><span> <%= opera.name %></span><span> <%= opera.amount %> </span></li>
  <% end %>
</ul>
</div>

app/views/groups/index.html.erb
<div class='mt-0' style='background-color: #3778c2'>
  <%= render 'shared/header' %>
  <h2 class='text-center bg-transparent fw-lighter text-white'>Most recent</h2>
</div>

<div class='row'>
<div class='col-4'>
<h2 class='text-secondary'>Gift</h2>
</div>
<div class='col-3'>
</div>
<div class='col-4'>
<h2 class='text-end text-secondary'>30 $</h2>
</div>
</div>

<div>
<% if @groups.empty? %>
  <span> No category yet </span>
<% else %>
  <% @groups.each do |g| %>
    <a href="<%= group_operations_group_path(g) %>">
    <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0 d-flex justify-content-between">
      <div class=" d-flex flex-row bd-highlight mb-3">
      <img src="<%= asset_path(g.icon) %>" alt="My Image">
      <span class="card-title text-secondary"><%= g.name %></span>
      <span class="card-title">(<%= g.group_total %>$)</span>
      </div>
      
    </div>
  </div>
    </a>
  <% end %>
<% end %>
</div>

app/views/groups/new.html.erb
<div class='mt-0' style='background-color: #3778c2'>
  <%= render 'shared/header' %>
</div>

<%= form_for @group do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control'  %>
  </div>
  <div class="mb-3">
    <%= f.label :icon, class: 'form-label' %>
    <%= f.select :icon, options_for_select([["Coca logo", "coca.png"], ["tongue logo", "langue.png"], ["pepsi", "pepsi.png"], ["Senders", "senders.png"], ["W logo", "w.png"]], "coca.png") ,class: 'form-select' %>

  </div>
 
  <div class="action">
    <%= f.submit 'Add Category', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/home/index.html.erb
<h1 class='h1 text-center' style='margin-top: 30%; margin-bottom: 30%;'>Transaction Web</h1>

  <div class="fixed-bottom" style='text-align: center'>
    <%= link_to "Login", new_user_session_path, class:'btn btn-primary text-white m-3'%><br>
    <%= link_to "Register", new_user_registration_path, class:'btn btn-primary text-white m-3' %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TransactionWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
    <p class="notice" ><%= notice %></p>
    <p class="alert" ><%= alert %></p>
  </body>
</html>

app/views/operations/new.html.erb
<div class='mt-0' style='background-color: #3778c2'>
  <%= render 'shared/header' %>
</div>
<%= form_with model: @operation do |form| %>
    <div class='mb-3'>
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class='mb-3'>
      <%= form.label :amount, class: 'form-label' %>
      <%= form.number_field :amount, class: 'form-control' %>
    </div>

    <%= fields_for :group_operation, @operation.group_operations.build do |group_form| %>
        <%= group_form.label :group_id %>
        <%= group_form.collection_select :group_id, Group.all, :id, :name, { prompt: 'Select a group' }, id: "group_select", class: 'form-select' %>
      <% end %>

      <%= form.hidden_field :extra_field, id: "extra_field_hidden" %>
    <div>
    <%= form.submit 'Save', class: 'btn btn-primary m-3' %>
    </div>

<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const groupSelect = document.getElementById("group_select");
    const extraFieldHidden = document.getElementById("extra_field_hidden");

    groupSelect.addEventListener("change", function () {
      const selectedGroupId = groupSelect.value;
      extraFieldHidden.value = selectedGroupId;
    });
  });
</script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent" >
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" ></span>
    </button>
    <a class="navbar-brand" href="<%= groups_path %>" style="color: #fff">Home</a>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= new_group_path %>" style="color: #fff">New Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_operation_path %>" style="color: #fff">New transaction</a>
        </li>
        
       
      </ul>
    </div>
  </div>
</nav>